### ISSUE TITLE
Udig developer documentation 

### ISSUE THREAD

**Issue by ebocher** [locationtech/udig-platform#296]
Hi,

I'd like to connect H2GIS (https://github.com/orbisgis/h2gis-geotools) with the UDIG (2.0.0).
I'm not able to find a documentation about that.
Could you please point me some resources...
Thanks

Ps : I tried to make a maven project based on the Postgis plugin but I can't compile it. I use the NetBeans IDE.

**Comment by fgdrf** [comment]
I'd suggest to follow csv tutorials (see https://github.com/locationtech/udig-platform/tree/master/plugins/org.locationtech.udig.tutorials.catalog.csv) to implement a new datastore/renderer

It looks like h2gis supports GeoTools 19.x++ we currently haven't integrated yet (see #279). Hope I understood it correctly : It provides a Datastore implementation?

If so, it might be possible to create a frament for udig.libs bundle (which provides all GeoTools libraries) which adds h2gis jar to classpath. At the end if you try to add a layer all Datastore implementations are displayed in Dialog.

Hope it helps

PS: I develop with Eclipse IDE because of OSGi and Eclipse specific target resolutions using P2 Repositories. NetBeans - My read - is perfect for pure Maven Projects...

**Comment by ebocher** [comment]
Thank you for your answer

The 0.1 version available on our maven repo is compatible with geotools 14.X
H2GISDatastore is clone of the PostGIS datastore.
I'm not very comfortable with the eclipse environment. My idea is to test H2GIS with UDIG and if it works maybe use it in the future and contribute to the community with my team.

Best regards

**Comment by ebocher** [comment]
Based on the PostGIS, I'm trying to make the connection with udig.
Currently, I'm not able to  handle dependencies correctly, so it does not compile if dependencies are not added manually.
https://github.com/ebocher/udig-platform/tree/h2gis_plugin/plugins/org.locationtech.udig.catalog.h2gis

**Comment by fgdrf** [comment]
Have a look at pom-libs.xml which are responsible for thirdparty dependency downloads via Maven. All other dependencies, especially Eclipse related are resolved via Eclipse target file definition. I assume no other IDE than Eclipse can handle it (in addition to Maven Tycho).

Maybe it helps. Since your request for support isn’t any issue for uDig itself, I‘ll close it.
